// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uazfmqkmuqmwuubfwtst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVhemZtcWttdXFtd3V1YmZ3dHN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY3ODgyNzcsImV4cCI6MjA1MjM2NDI3N30.RCNwxhkEDKpn3hJFnUnm832UOIJmU3wraGvKbp_n2XY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});